# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true
# Project
parchment_minecraft_version = 1.21.8
parchment_mappings_version = 2025.09.14
minecraft_version = 1.21.8
minecraft_version_range = [1.21.8, 1.22)
neo_version = 21.8.10
neo_version_range = [21.8.0,)
loader_version_range = [4,)
# Mod
mod_id = quicksand
mod_artifact_id = quicksand-neoforge
mod_name = Quicksand
mod_license = LGPL-3.0-or-later
mod_version = 2.0.0
mod_group_id = plus.dragons.quicksand
mod_authors = DragonsPlus
mod_description = A mod adding quicksand to Minecraft.
mod_github = https://github.com/DragonsPlusMinecraft/Quicksand
mod_logo = icon.png
# Mod Dependencies
bwg_version = 4.0.1-NeoForge
jade_version = 19.3.1+neoforge
wthit_version = 16.0.1
